// 世界の国データベース（EarthWISE 世界の国チャンピオン）
// c:国名 / cap:首都 / en:地図データ上の英語名(なければnull=マーカー表示) / cont:大陸
// tier:難易度(1=小,2=中,3=高) / fam:名物・有名なもの(配列) / exp:主な輸出品
// flag:国旗 / lon,lat:首都のおおよその経度・緯度 / size:面積カテゴリ(L/M/S)＝ズーム量
// ※首都は正確さ重視。名物・輸出品は学習用の代表例なので自由に編集できます。
const COUNTRIES = [
  // ===================== アジア =====================
  { c:"日本", cap:"東京", en:"Japan", cont:"アジア", tier:1, fam:["寿司","富士山","アニメ","桜","新幹線"], exp:"自動車", flag:"🇯🇵", lon:139.7, lat:35.7, size:"M" },
  { c:"中国", cap:"ペキン（北京）", en:"China", cont:"アジア", tier:1, fam:["万里の長城","パンダ","餃子","シルクロード","兵馬俑"], exp:"電子機器", flag:"🇨🇳", lon:116.4, lat:39.9, size:"L" },
  { c:"韓国", cap:"ソウル", en:"South Korea", cont:"アジア", tier:1, fam:["キムチ","K-POP"], exp:"半導体", flag:"🇰🇷", lon:127.0, lat:37.5, size:"M" },
  { c:"北朝鮮", cap:"ピョンヤン（平壌）", en:"North Korea", cont:"アジア", tier:3, fam:["冷麺"], exp:"石炭", flag:"🇰🇵", lon:125.75, lat:39.03, size:"M" },
  { c:"インド", cap:"ニューデリー", en:"India", cont:"アジア", tier:1, fam:["タージ・マハル","カレー","ヨガ","ガンジス川","象"], exp:"ソフトウェア", flag:"🇮🇳", lon:77.2, lat:28.6, size:"L" },
  { c:"タイ", cap:"バンコク", en:"Thailand", cont:"アジア", tier:2, fam:["トムヤムクン","象","ムエタイ"], exp:"米", flag:"🇹🇭", lon:100.5, lat:13.75, size:"M" },
  { c:"ベトナム", cap:"ハノイ", en:"Vietnam", cont:"アジア", tier:2, fam:["フォー","アオザイ"], exp:"コーヒー", flag:"🇻🇳", lon:105.85, lat:21.0, size:"M" },
  { c:"インドネシア", cap:"ジャカルタ", en:"Indonesia", cont:"アジア", tier:2, fam:["バリ島","オランウータン"], exp:"パーム油", flag:"🇮🇩", lon:106.8, lat:-6.2, size:"L" },
  { c:"フィリピン", cap:"マニラ", en:"Philippines", cont:"アジア", tier:2, fam:["バナナ","セブ島"], exp:"電子機器", flag:"🇵🇭", lon:121.0, lat:14.6, size:"M" },
  { c:"マレーシア", cap:"クアラルンプール", en:"Malaysia", cont:"アジア", tier:2, fam:["ペトロナスタワー"], exp:"パーム油", flag:"🇲🇾", lon:101.7, lat:3.14, size:"M" },
  { c:"シンガポール", cap:"シンガポール", en:null, cont:"アジア", tier:2, fam:["マーライオン","チキンライス"], exp:"電子機器", flag:"🇸🇬", lon:103.82, lat:1.35, size:"S" },
  { c:"ミャンマー", cap:"ネピドー", en:"Myanmar", cont:"アジア", tier:3, fam:["パゴダ"], exp:"天然ガス", flag:"🇲🇲", lon:96.13, lat:19.75, size:"M" },
  { c:"カンボジア", cap:"プノンペン", en:"Cambodia", cont:"アジア", tier:3, fam:["アンコール・ワット"], exp:"衣料品", flag:"🇰🇭", lon:104.9, lat:11.6, size:"M" },
  { c:"ラオス", cap:"ビエンチャン", en:"Laos", cont:"アジア", tier:3, fam:["メコン川"], exp:"銅", flag:"🇱🇦", lon:102.6, lat:17.97, size:"M" },
  { c:"ブルネイ", cap:"バンダルスリブガワン", en:"Brunei", cont:"アジア", tier:3, fam:["黄金のモスク"], exp:"石油", flag:"🇧🇳", lon:114.94, lat:4.94, size:"S" },
  { c:"モンゴル", cap:"ウランバートル", en:"Mongolia", cont:"アジア", tier:2, fam:["ゲル","遊牧","相撲"], exp:"石炭", flag:"🇲🇳", lon:106.9, lat:47.9, size:"L" },
  { c:"ネパール", cap:"カトマンズ", en:"Nepal", cont:"アジア", tier:3, fam:["エベレスト"], exp:"カーペット", flag:"🇳🇵", lon:85.3, lat:27.7, size:"M" },
  { c:"ブータン", cap:"ティンプー", en:"Bhutan", cont:"アジア", tier:3, fam:["幸福の国","ゾンカ"], exp:"電力", flag:"🇧🇹", lon:89.63, lat:27.47, size:"S" },
  { c:"スリランカ", cap:"スリジャヤワルダナプラコッテ", en:"Sri Lanka", cont:"アジア", tier:3, fam:["セイロン紅茶"], exp:"紅茶", flag:"🇱🇰", lon:79.9, lat:6.9, size:"M" },
  { c:"バングラデシュ", cap:"ダッカ", en:"Bangladesh", cont:"アジア", tier:3, fam:["ベンガルタイガー"], exp:"衣料品", flag:"🇧🇩", lon:90.4, lat:23.8, size:"M" },
  { c:"パキスタン", cap:"イスラマバード", en:"Pakistan", cont:"アジア", tier:2, fam:["インダス文明"], exp:"繊維製品", flag:"🇵🇰", lon:73.0, lat:33.7, size:"M" },
  { c:"アフガニスタン", cap:"カブール", en:"Afghanistan", cont:"アジア", tier:3, fam:["ヒンドゥークシュ山脈"], exp:"じゅうたん", flag:"🇦🇫", lon:69.18, lat:34.53, size:"M" },
  { c:"カザフスタン", cap:"アスタナ", en:"Kazakhstan", cont:"アジア", tier:3, fam:["ステップ","バイコヌール宇宙基地"], exp:"石油", flag:"🇰🇿", lon:71.43, lat:51.13, size:"L" },
  { c:"ウズベキスタン", cap:"タシケント", en:"Uzbekistan", cont:"アジア", tier:3, fam:["サマルカンド"], exp:"金", flag:"🇺🇿", lon:69.24, lat:41.31, size:"M" },
  { c:"サウジアラビア", cap:"リヤド", en:"Saudi Arabia", cont:"アジア", tier:2, fam:["メッカ巡礼","砂漠"], exp:"石油", flag:"🇸🇦", lon:46.7, lat:24.7, size:"L" },
  { c:"アラブ首長国連邦", cap:"アブダビ", en:"United Arab Emirates", cont:"アジア", tier:2, fam:["ドバイの高層ビル","砂漠"], exp:"石油", flag:"🇦🇪", lon:54.4, lat:24.5, size:"S" },
  { c:"イラン", cap:"テヘラン", en:"Iran", cont:"アジア", tier:2, fam:["ペルシャ絨毯"], exp:"石油", flag:"🇮🇷", lon:51.4, lat:35.7, size:"L" },
  { c:"イラク", cap:"バグダッド", en:"Iraq", cont:"アジア", tier:3, fam:["メソポタミア文明"], exp:"石油", flag:"🇮🇶", lon:44.4, lat:33.3, size:"M" },
  { c:"トルコ", cap:"アンカラ", en:"Turkey", cont:"アジア", tier:2, fam:["バザール","ケバブ"], exp:"繊維製品", flag:"🇹🇷", lon:32.85, lat:39.9, size:"M" },
  { c:"イスラエル", cap:"エルサレム", en:"Israel", cont:"アジア", tier:2, fam:["嘆きの壁","死海"], exp:"ダイヤ・電子機器", flag:"🇮🇱", lon:35.22, lat:31.78, size:"S" },
  { c:"ヨルダン", cap:"アンマン", en:"Jordan", cont:"アジア", tier:3, fam:["ペトラ遺跡"], exp:"リン鉱石", flag:"🇯🇴", lon:35.93, lat:31.95, size:"S" },
  { c:"レバノン", cap:"ベイルート", en:"Lebanon", cont:"アジア", tier:3, fam:["杉の木"], exp:"宝飾品", flag:"🇱🇧", lon:35.5, lat:33.9, size:"S" },
  { c:"シリア", cap:"ダマスカス", en:"Syria", cont:"アジア", tier:3, fam:["古代都市"], exp:"石油", flag:"🇸🇾", lon:36.3, lat:33.51, size:"M" },
  { c:"カタール", cap:"ドーハ", en:"Qatar", cont:"アジア", tier:3, fam:["砂漠","近代都市"], exp:"天然ガス", flag:"🇶🇦", lon:51.53, lat:25.29, size:"S" },
  { c:"クウェート", cap:"クウェート", en:"Kuwait", cont:"アジア", tier:3, fam:["石油の国"], exp:"石油", flag:"🇰🇼", lon:47.98, lat:29.37, size:"S" },
  { c:"オマーン", cap:"マスカット", en:"Oman", cont:"アジア", tier:3, fam:["乳香"], exp:"石油", flag:"🇴🇲", lon:58.4, lat:23.6, size:"M" },
  { c:"イエメン", cap:"サヌア", en:"Yemen", cont:"アジア", tier:3, fam:["コーヒー発祥の港モカ"], exp:"石油", flag:"🇾🇪", lon:44.2, lat:15.35, size:"M" },
  { c:"ジョージア", cap:"トビリシ", en:"Georgia", cont:"アジア", tier:3, fam:["コーカサス","ワイン発祥"], exp:"ワイン", flag:"🇬🇪", lon:44.8, lat:41.72, size:"S" },

  // ===================== ヨーロッパ =====================
  { c:"イギリス", cap:"ロンドン", en:"United Kingdom", cont:"ヨーロッパ", tier:1, fam:["ビッグ・ベン","二階建てバス","サッカー","アフタヌーンティー","ハリー・ポッター"], exp:"機械類", flag:"🇬🇧", lon:-0.13, lat:51.5, size:"M" },
  { c:"フランス", cap:"パリ", en:"France", cont:"ヨーロッパ", tier:1, fam:["エッフェル塔","ルーブル美術館","ワイン","凱旋門","モナリザ"], exp:"ワイン", flag:"🇫🇷", lon:2.35, lat:48.85, size:"M" },
  { c:"ドイツ", cap:"ベルリン", en:"Germany", cont:"ヨーロッパ", tier:1, fam:["ソーセージ","ビール","自動車","オクトーバーフェスト","ノイシュヴァンシュタイン城"], exp:"自動車", flag:"🇩🇪", lon:13.4, lat:52.5, size:"M" },
  { c:"イタリア", cap:"ローマ", en:"Italy", cont:"ヨーロッパ", tier:1, fam:["コロッセオ","パスタ","ピザ"], exp:"ファッション", flag:"🇮🇹", lon:12.5, lat:41.9, size:"M" },
  { c:"スペイン", cap:"マドリード", en:"Spain", cont:"ヨーロッパ", tier:1, fam:["サグラダ・ファミリア","フラメンコ","闘牛"], exp:"オリーブ油", flag:"🇪🇸", lon:-3.7, lat:40.4, size:"M" },
  { c:"ポルトガル", cap:"リスボン", en:"Portugal", cont:"ヨーロッパ", tier:2, fam:["ポートワイン","エッグタルト"], exp:"コルク", flag:"🇵🇹", lon:-9.14, lat:38.7, size:"S" },
  { c:"オランダ", cap:"アムステルダム", en:"Netherlands", cont:"ヨーロッパ", tier:2, fam:["風車","チューリップ","運河"], exp:"切り花", flag:"🇳🇱", lon:4.9, lat:52.37, size:"S" },
  { c:"ベルギー", cap:"ブリュッセル", en:"Belgium", cont:"ヨーロッパ", tier:2, fam:["チョコ","ワッフル","小便小僧"], exp:"医薬品", flag:"🇧🇪", lon:4.35, lat:50.85, size:"S" },
  { c:"スイス", cap:"ベルン", en:"Switzerland", cont:"ヨーロッパ", tier:2, fam:["アルプス","時計","チーズ"], exp:"精密機械", flag:"🇨🇭", lon:7.45, lat:46.95, size:"S" },
  { c:"オーストリア", cap:"ウィーン", en:"Austria", cont:"ヨーロッパ", tier:2, fam:["音楽の都","ザッハトルテ"], exp:"機械類", flag:"🇦🇹", lon:16.37, lat:48.2, size:"S" },
  { c:"ギリシャ", cap:"アテネ", en:"Greece", cont:"ヨーロッパ", tier:2, fam:["パルテノン神殿","エーゲ海"], exp:"オリーブ油", flag:"🇬🇷", lon:23.7, lat:37.98, size:"M" },
  { c:"ロシア", cap:"モスクワ", en:"Russia", cont:"ヨーロッパ", tier:1, fam:["赤の広場","マトリョーシカ"], exp:"天然ガス", flag:"🇷🇺", lon:37.6, lat:55.75, size:"L" },
  { c:"スウェーデン", cap:"ストックホルム", en:"Sweden", cont:"ヨーロッパ", tier:2, fam:["オーロラ","北欧家具","ノーベル賞"], exp:"自動車", flag:"🇸🇪", lon:18.07, lat:59.33, size:"M" },
  { c:"ノルウェー", cap:"オスロ", en:"Norway", cont:"ヨーロッパ", tier:2, fam:["フィヨルド","サーモン"], exp:"石油・魚", flag:"🇳🇴", lon:10.75, lat:59.9, size:"M" },
  { c:"フィンランド", cap:"ヘルシンキ", en:"Finland", cont:"ヨーロッパ", tier:2, fam:["サウナ","ムーミン","サンタクロース"], exp:"紙・パルプ", flag:"🇫🇮", lon:24.94, lat:60.17, size:"M" },
  { c:"デンマーク", cap:"コペンハーゲン", en:"Denmark", cont:"ヨーロッパ", tier:2, fam:["人魚姫の像","レゴ"], exp:"豚肉", flag:"🇩🇰", lon:12.57, lat:55.68, size:"S" },
  { c:"アイスランド", cap:"レイキャビク", en:"Iceland", cont:"ヨーロッパ", tier:3, fam:["オーロラ","温泉","間欠泉"], exp:"魚", flag:"🇮🇸", lon:-21.9, lat:64.15, size:"M" },
  { c:"アイルランド", cap:"ダブリン", en:"Ireland", cont:"ヨーロッパ", tier:2, fam:["ケルト文化","ギネスビール"], exp:"医薬品", flag:"🇮🇪", lon:-6.26, lat:53.35, size:"S" },
  { c:"ポーランド", cap:"ワルシャワ", en:"Poland", cont:"ヨーロッパ", tier:2, fam:["ショパン","琥珀"], exp:"機械類", flag:"🇵🇱", lon:21.0, lat:52.23, size:"M" },
  { c:"チェコ", cap:"プラハ", en:"Czechia", cont:"ヨーロッパ", tier:2, fam:["ビール","美しい古都"], exp:"自動車", flag:"🇨🇿", lon:14.42, lat:50.09, size:"S" },
  { c:"ハンガリー", cap:"ブダペスト", en:"Hungary", cont:"ヨーロッパ", tier:3, fam:["温泉","グヤーシュ"], exp:"機械類", flag:"🇭🇺", lon:19.04, lat:47.5, size:"S" },
  { c:"ルーマニア", cap:"ブカレスト", en:"Romania", cont:"ヨーロッパ", tier:3, fam:["ドラキュラ城"], exp:"機械類", flag:"🇷🇴", lon:26.1, lat:44.43, size:"M" },
  { c:"ブルガリア", cap:"ソフィア", en:"Bulgaria", cont:"ヨーロッパ", tier:3, fam:["ヨーグルト","バラ"], exp:"バラ油", flag:"🇧🇬", lon:23.32, lat:42.7, size:"S" },
  { c:"ウクライナ", cap:"キーウ", en:"Ukraine", cont:"ヨーロッパ", tier:2, fam:["ひまわり畑"], exp:"小麦", flag:"🇺🇦", lon:30.5, lat:50.45, size:"M" },
  { c:"クロアチア", cap:"ザグレブ", en:"Croatia", cont:"ヨーロッパ", tier:3, fam:["アドリア海","ドブロブニク"], exp:"船舶", flag:"🇭🇷", lon:15.98, lat:45.81, size:"S" },
  { c:"セルビア", cap:"ベオグラード", en:"Serbia", cont:"ヨーロッパ", tier:3, fam:["ドナウ川"], exp:"果物", flag:"🇷🇸", lon:20.46, lat:44.82, size:"S" },
  { c:"スロバキア", cap:"ブラチスラバ", en:"Slovakia", cont:"ヨーロッパ", tier:3, fam:["タトラ山脈"], exp:"自動車", flag:"🇸🇰", lon:17.11, lat:48.15, size:"S" },
  { c:"スロベニア", cap:"リュブリャナ", en:"Slovenia", cont:"ヨーロッパ", tier:3, fam:["ブレッド湖"], exp:"自動車", flag:"🇸🇮", lon:14.51, lat:46.05, size:"S" },
  { c:"リトアニア", cap:"ビリニュス", en:"Lithuania", cont:"ヨーロッパ", tier:3, fam:["琥珀"], exp:"石油製品", flag:"🇱🇹", lon:25.28, lat:54.69, size:"S" },
  { c:"ラトビア", cap:"リガ", en:"Latvia", cont:"ヨーロッパ", tier:3, fam:["バルト海","森"], exp:"木材", flag:"🇱🇻", lon:24.11, lat:56.95, size:"S" },
  { c:"エストニア", cap:"タリン", en:"Estonia", cont:"ヨーロッパ", tier:3, fam:["電子国家","中世の街"], exp:"電子機器", flag:"🇪🇪", lon:24.75, lat:59.44, size:"S" },
  { c:"ベラルーシ", cap:"ミンスク", en:"Belarus", cont:"ヨーロッパ", tier:3, fam:["森と湖"], exp:"カリ肥料", flag:"🇧🇾", lon:27.56, lat:53.9, size:"M" },
  { c:"ルクセンブルク", cap:"ルクセンブルク", en:"Luxembourg", cont:"ヨーロッパ", tier:3, fam:["金融の国"], exp:"鉄鋼", flag:"🇱🇺", lon:6.13, lat:49.61, size:"S" },

  // ===================== アフリカ =====================
  { c:"エジプト", cap:"カイロ", en:"Egypt", cont:"アフリカ", tier:1, fam:["ピラミッド","スフィンクス","ナイル川"], exp:"石油", flag:"🇪🇬", lon:31.2, lat:30.05, size:"L" },
  { c:"南アフリカ", cap:"プレトリア", en:"South Africa", cont:"アフリカ", tier:1, fam:["サバンナ","金","ダイヤ"], exp:"金・ダイヤ", flag:"🇿🇦", lon:28.2, lat:-25.75, size:"L" },
  { c:"モロッコ", cap:"ラバト", en:"Morocco", cont:"アフリカ", tier:2, fam:["サハラ砂漠","青い街"], exp:"リン鉱石", flag:"🇲🇦", lon:-6.84, lat:34.02, size:"M" },
  { c:"アルジェリア", cap:"アルジェ", en:"Algeria", cont:"アフリカ", tier:3, fam:["サハラ砂漠"], exp:"天然ガス", flag:"🇩🇿", lon:3.06, lat:36.75, size:"L" },
  { c:"チュニジア", cap:"チュニス", en:"Tunisia", cont:"アフリカ", tier:3, fam:["カルタゴ遺跡"], exp:"オリーブ油", flag:"🇹🇳", lon:10.18, lat:36.8, size:"M" },
  { c:"リビア", cap:"トリポリ", en:"Libya", cont:"アフリカ", tier:3, fam:["サハラ砂漠"], exp:"石油", flag:"🇱🇾", lon:13.19, lat:32.9, size:"L" },
  { c:"ケニア", cap:"ナイロビ", en:"Kenya", cont:"アフリカ", tier:2, fam:["サファリ","マサイ族","マラソン"], exp:"紅茶", flag:"🇰🇪", lon:36.8, lat:-1.29, size:"M" },
  { c:"タンザニア", cap:"ドドマ", en:"Tanzania", cont:"アフリカ", tier:2, fam:["キリマンジャロ","セレンゲティ"], exp:"金", flag:"🇹🇿", lon:35.75, lat:-6.17, size:"L" },
  { c:"エチオピア", cap:"アディスアベバ", en:"Ethiopia", cont:"アフリカ", tier:2, fam:["コーヒー発祥"], exp:"コーヒー", flag:"🇪🇹", lon:38.7, lat:9.0, size:"L" },
  { c:"ナイジェリア", cap:"アブジャ", en:"Nigeria", cont:"アフリカ", tier:2, fam:["アフリカ最大の人口"], exp:"石油", flag:"🇳🇬", lon:7.5, lat:9.06, size:"M" },
  { c:"ガーナ", cap:"アクラ", en:"Ghana", cont:"アフリカ", tier:2, fam:["カカオ"], exp:"カカオ", flag:"🇬🇭", lon:-0.19, lat:5.6, size:"M" },
  { c:"セネガル", cap:"ダカール", en:"Senegal", cont:"アフリカ", tier:3, fam:["ダカール・ラリー"], exp:"魚・落花生", flag:"🇸🇳", lon:-17.45, lat:14.7, size:"M" },
  { c:"コートジボワール", cap:"ヤムスクロ", en:"Côte d'Ivoire", cont:"アフリカ", tier:3, fam:["カカオ世界一"], exp:"カカオ", flag:"🇨🇮", lon:-5.28, lat:6.82, size:"M" },
  { c:"カメルーン", cap:"ヤウンデ", en:"Cameroon", cont:"アフリカ", tier:3, fam:["サッカー"], exp:"石油", flag:"🇨🇲", lon:11.5, lat:3.87, size:"M" },
  { c:"スーダン", cap:"ハルツーム", en:"Sudan", cont:"アフリカ", tier:3, fam:["ナイル川の合流点"], exp:"ゴマ", flag:"🇸🇩", lon:32.5, lat:15.5, size:"L" },
  { c:"ウガンダ", cap:"カンパラ", en:"Uganda", cont:"アフリカ", tier:3, fam:["マウンテンゴリラ"], exp:"コーヒー", flag:"🇺🇬", lon:32.58, lat:0.32, size:"M" },
  { c:"ジンバブエ", cap:"ハラレ", en:"Zimbabwe", cont:"アフリカ", tier:3, fam:["ビクトリアの滝"], exp:"タバコ", flag:"🇿🇼", lon:31.05, lat:-17.83, size:"M" },
  { c:"ザンビア", cap:"ルサカ", en:"Zambia", cont:"アフリカ", tier:3, fam:["ビクトリアの滝"], exp:"銅", flag:"🇿🇲", lon:28.32, lat:-15.42, size:"M" },
  { c:"モザンビーク", cap:"マプト", en:"Mozambique", cont:"アフリカ", tier:3, fam:["インド洋のビーチ"], exp:"アルミ", flag:"🇲🇿", lon:32.57, lat:-25.97, size:"M" },
  { c:"アンゴラ", cap:"ルアンダ", en:"Angola", cont:"アフリカ", tier:3, fam:["大西洋岸"], exp:"石油", flag:"🇦🇴", lon:13.23, lat:-8.84, size:"L" },
  { c:"マダガスカル", cap:"アンタナナリボ", en:"Madagascar", cont:"アフリカ", tier:2, fam:["キツネザル","バオバブ"], exp:"バニラ", flag:"🇲🇬", lon:47.5, lat:-18.9, size:"M" },
  { c:"ボツワナ", cap:"ハボローネ", en:"Botswana", cont:"アフリカ", tier:3, fam:["カラハリ砂漠","ダイヤ"], exp:"ダイヤ", flag:"🇧🇼", lon:25.9, lat:-24.65, size:"M" },
  { c:"ナミビア", cap:"ウィントフック", en:"Namibia", cont:"アフリカ", tier:3, fam:["ナミブ砂漠"], exp:"ダイヤ", flag:"🇳🇦", lon:17.08, lat:-22.56, size:"M" },
  { c:"ルワンダ", cap:"キガリ", en:"Rwanda", cont:"アフリカ", tier:3, fam:["千の丘の国","ゴリラ"], exp:"コーヒー", flag:"🇷🇼", lon:30.06, lat:-1.95, size:"S" },
  { c:"マリ", cap:"バマコ", en:"Mali", cont:"アフリカ", tier:3, fam:["トンブクトゥ"], exp:"金", flag:"🇲🇱", lon:-8.0, lat:12.65, size:"L" },
  { c:"コンゴ民主共和国", cap:"キンシャサ", en:"Dem. Rep. Congo", cont:"アフリカ", tier:3, fam:["コンゴ川","熱帯雨林"], exp:"銅・コバルト", flag:"🇨🇩", lon:15.31, lat:-4.32, size:"L" },

  // ===================== 北アメリカ =====================
  { c:"アメリカ", cap:"ワシントンD.C.", en:"United States of America", cont:"北アメリカ", tier:1, fam:["自由の女神","ハリウッド","ハンバーガー","グランドキャニオン","ジーンズ"], exp:"航空機", flag:"🇺🇸", lon:-77.04, lat:38.9, size:"L" },
  { c:"カナダ", cap:"オタワ", en:"Canada", cont:"北アメリカ", tier:1, fam:["メープルシロップ","ナイアガラの滝"], exp:"木材・石油", flag:"🇨🇦", lon:-75.7, lat:45.4, size:"L" },
  { c:"メキシコ", cap:"メキシコシティ", en:"Mexico", cont:"北アメリカ", tier:1, fam:["タコス","マヤ・アステカ","ソンブレロ"], exp:"自動車", flag:"🇲🇽", lon:-99.13, lat:19.43, size:"L" },
  { c:"キューバ", cap:"ハバナ", en:"Cuba", cont:"北アメリカ", tier:2, fam:["葉巻","サルサ"], exp:"葉巻・砂糖", flag:"🇨🇺", lon:-82.38, lat:23.13, size:"S" },
  { c:"ジャマイカ", cap:"キングストン", en:"Jamaica", cont:"北アメリカ", tier:2, fam:["レゲエ","ボルト"], exp:"アルミナ", flag:"🇯🇲", lon:-76.79, lat:17.99, size:"S" },
  { c:"パナマ", cap:"パナマシティ", en:"Panama", cont:"北アメリカ", tier:2, fam:["パナマ運河","パナマ帽"], exp:"バナナ", flag:"🇵🇦", lon:-79.53, lat:8.98, size:"S" },
  { c:"グアテマラ", cap:"グアテマラシティ", en:"Guatemala", cont:"北アメリカ", tier:3, fam:["マヤ文明","ティカル遺跡"], exp:"コーヒー", flag:"🇬🇹", lon:-90.5, lat:14.6, size:"M" },
  { c:"コスタリカ", cap:"サンホセ", en:"Costa Rica", cont:"北アメリカ", tier:3, fam:["熱帯雨林","エコツアー"], exp:"コーヒー・バナナ", flag:"🇨🇷", lon:-84.08, lat:9.93, size:"S" },
  { c:"ホンジュラス", cap:"テグシガルパ", en:"Honduras", cont:"北アメリカ", tier:3, fam:["マヤ遺跡コパン"], exp:"コーヒー", flag:"🇭🇳", lon:-87.2, lat:14.1, size:"M" },
  { c:"ニカラグア", cap:"マナグア", en:"Nicaragua", cont:"北アメリカ", tier:3, fam:["火山と湖"], exp:"コーヒー", flag:"🇳🇮", lon:-86.25, lat:12.14, size:"M" },
  { c:"エルサルバドル", cap:"サンサルバドル", en:"El Salvador", cont:"北アメリカ", tier:3, fam:["火山の国","ププサ"], exp:"コーヒー", flag:"🇸🇻", lon:-89.19, lat:13.69, size:"S" },
  { c:"ドミニカ共和国", cap:"サントドミンゴ", en:"Dominican Rep.", cont:"北アメリカ", tier:3, fam:["カリブのリゾート","野球"], exp:"葉巻", flag:"🇩🇴", lon:-69.9, lat:18.47, size:"S" },
  { c:"ハイチ", cap:"ポルトープランス", en:"Haiti", cont:"北アメリカ", tier:3, fam:["カリブ海の国"], exp:"衣料品", flag:"🇭🇹", lon:-72.34, lat:18.54, size:"S" },
  { c:"バハマ", cap:"ナッソー", en:"Bahamas", cont:"北アメリカ", tier:3, fam:["ピンクの砂浜"], exp:"観光", flag:"🇧🇸", lon:-77.35, lat:25.06, size:"S" },
  { c:"トリニダード・トバゴ", cap:"ポートオブスペイン", en:"Trinidad and Tobago", cont:"北アメリカ", tier:3, fam:["カーニバル","スチールパン"], exp:"天然ガス", flag:"🇹🇹", lon:-61.52, lat:10.66, size:"S" },

  // ===================== 南アメリカ =====================
  { c:"ブラジル", cap:"ブラジリア", en:"Brazil", cont:"南アメリカ", tier:1, fam:["サッカー","アマゾン","カーニバル"], exp:"大豆・鉄鉱石", flag:"🇧🇷", lon:-47.9, lat:-15.8, size:"L" },
  { c:"アルゼンチン", cap:"ブエノスアイレス", en:"Argentina", cont:"南アメリカ", tier:1, fam:["タンゴ","牛肉","サッカー"], exp:"大豆", flag:"🇦🇷", lon:-58.4, lat:-34.6, size:"L" },
  { c:"ペルー", cap:"リマ", en:"Peru", cont:"南アメリカ", tier:2, fam:["マチュ・ピチュ","ナスカの地上絵","アルパカ"], exp:"銅", flag:"🇵🇪", lon:-77.03, lat:-12.05, size:"L" },
  { c:"チリ", cap:"サンティアゴ", en:"Chile", cont:"南アメリカ", tier:2, fam:["アンデス山脈","イースター島"], exp:"銅", flag:"🇨🇱", lon:-70.65, lat:-33.45, size:"L" },
  { c:"コロンビア", cap:"ボゴタ", en:"Colombia", cont:"南アメリカ", tier:2, fam:["コーヒー","エメラルド"], exp:"石油・コーヒー", flag:"🇨🇴", lon:-74.07, lat:4.7, size:"L" },
  { c:"ベネズエラ", cap:"カラカス", en:"Venezuela", cont:"南アメリカ", tier:3, fam:["ギアナ高地","エンジェルフォール"], exp:"石油", flag:"🇻🇪", lon:-66.9, lat:10.5, size:"L" },
  { c:"エクアドル", cap:"キト", en:"Ecuador", cont:"南アメリカ", tier:3, fam:["ガラパゴス諸島","赤道"], exp:"バナナ・石油", flag:"🇪🇨", lon:-78.5, lat:-0.18, size:"M" },
  { c:"ボリビア", cap:"スクレ", en:"Bolivia", cont:"南アメリカ", tier:3, fam:["ウユニ塩湖","チチカカ湖"], exp:"天然ガス", flag:"🇧🇴", lon:-65.26, lat:-19.03, size:"L" },
  { c:"ウルグアイ", cap:"モンテビデオ", en:"Uruguay", cont:"南アメリカ", tier:3, fam:["牛肉大国","サッカー"], exp:"牛肉・大豆", flag:"🇺🇾", lon:-56.19, lat:-34.9, size:"M" },
  { c:"パラグアイ", cap:"アスンシオン", en:"Paraguay", cont:"南アメリカ", tier:3, fam:["イグアスの滝","マテ茶"], exp:"大豆", flag:"🇵🇾", lon:-57.6, lat:-25.3, size:"M" },

  // ===================== オセアニア =====================
  { c:"オーストラリア", cap:"キャンベラ", en:"Australia", cont:"オセアニア", tier:1, fam:["コアラ","カンガルー","エアーズロック","グレートバリアリーフ","オペラハウス"], exp:"鉄鉱石・石炭", flag:"🇦🇺", lon:149.13, lat:-35.28, size:"L" },
  { c:"ニュージーランド", cap:"ウェリントン", en:"New Zealand", cont:"オセアニア", tier:1, fam:["羊","キウイ","ラグビー"], exp:"乳製品・羊毛", flag:"🇳🇿", lon:174.78, lat:-41.29, size:"M" },
  { c:"フィジー", cap:"スバ", en:"Fiji", cont:"オセアニア", tier:2, fam:["南国リゾート","サンゴ礁"], exp:"砂糖", flag:"🇫🇯", lon:178.44, lat:-18.14, size:"S" },
  { c:"パプアニューギニア", cap:"ポートモレスビー", en:"Papua New Guinea", cont:"オセアニア", tier:2, fam:["800以上の言語","極楽鳥"], exp:"金・天然ガス", flag:"🇵🇬", lon:147.19, lat:-9.44, size:"M" },
  { c:"サモア", cap:"アピア", en:null, cont:"オセアニア", tier:3, fam:["南太平洋の島国"], exp:"魚・ココナッツ", flag:"🇼🇸", lon:-171.75, lat:-13.83, size:"S" },
  { c:"トンガ", cap:"ヌクアロファ", en:null, cont:"オセアニア", tier:3, fam:["太平洋の王国"], exp:"かぼちゃ・魚", flag:"🇹🇴", lon:-175.2, lat:-21.13, size:"S" },
  { c:"ソロモン諸島", cap:"ホニアラ", en:"Solomon Is.", cont:"オセアニア", tier:3, fam:["第二次大戦の激戦地"], exp:"木材", flag:"🇸🇧", lon:159.95, lat:-9.43, size:"S" },
  { c:"バヌアツ", cap:"ポートビラ", en:"Vanuatu", cont:"オセアニア", tier:3, fam:["火山の島","バンジー発祥"], exp:"コプラ", flag:"🇻🇺", lon:168.32, lat:-17.73, size:"S" },
  { c:"パラオ", cap:"マルキョク", en:null, cont:"オセアニア", tier:3, fam:["ダイビング","くらげの湖"], exp:"魚", flag:"🇵🇼", lon:134.62, lat:7.5, size:"S" },
  { c:"ミクロネシア", cap:"パリキール", en:null, cont:"オセアニア", tier:3, fam:["ナンマトル遺跡"], exp:"魚", flag:"🇫🇲", lon:158.16, lat:6.92, size:"S" },
  { c:"キリバス", cap:"タラワ", en:null, cont:"オセアニア", tier:3, fam:["日付変更線の島"], exp:"魚", flag:"🇰🇮", lon:173.02, lat:1.33, size:"S" },
  { c:"マーシャル諸島", cap:"マジュロ", en:null, cont:"オセアニア", tier:3, fam:["環礁の国"], exp:"魚", flag:"🇲🇭", lon:171.38, lat:7.09, size:"S" },
  { c:"ツバル", cap:"フナフティ", en:null, cont:"オセアニア", tier:3, fam:["海面上昇で有名","切手"], exp:"ドメイン(.tv)", flag:"🇹🇻", lon:179.2, lat:-8.52, size:"S" },
  { c:"ナウル", cap:"ヤレン", en:null, cont:"オセアニア", tier:3, fam:["世界最小級の島国"], exp:"リン鉱石", flag:"🇳🇷", lon:166.92, lat:-0.55, size:"S" },

  // ===================== アジア（追加） =====================
  { c:"トルクメニスタン", cap:"アシガバット", en:"Turkmenistan", cont:"アジア", tier:3, fam:["カラクム砂漠","白い大理石の都"], exp:"天然ガス", flag:"🇹🇲", lon:58.38, lat:37.95, size:"M" },
  { c:"タジキスタン", cap:"ドゥシャンベ", en:"Tajikistan", cont:"アジア", tier:3, fam:["パミール高原"], exp:"アルミ", flag:"🇹🇯", lon:68.78, lat:38.56, size:"M" },
  { c:"キルギス", cap:"ビシュケク", en:"Kyrgyzstan", cont:"アジア", tier:3, fam:["天山山脈","遊牧"], exp:"金", flag:"🇰🇬", lon:74.6, lat:42.87, size:"M" },
  { c:"アルメニア", cap:"エレバン", en:"Armenia", cont:"アジア", tier:3, fam:["アララト山","世界最古のキリスト教国"], exp:"銅", flag:"🇦🇲", lon:44.51, lat:40.18, size:"S" },
  { c:"アゼルバイジャン", cap:"バクー", en:"Azerbaijan", cont:"アジア", tier:3, fam:["火の国","カスピ海"], exp:"石油", flag:"🇦🇿", lon:49.87, lat:40.41, size:"S" },
  { c:"バーレーン", cap:"マナーマ", en:null, cont:"アジア", tier:3, fam:["真珠","F1"], exp:"石油", flag:"🇧🇭", lon:50.59, lat:26.23, size:"S" },
  { c:"モルディブ", cap:"マレ", en:null, cont:"アジア", tier:2, fam:["水上コテージ","サンゴ礁"], exp:"魚", flag:"🇲🇻", lon:73.51, lat:4.17, size:"S" },
  { c:"東ティモール", cap:"ディリ", en:"Timor-Leste", cont:"アジア", tier:3, fam:["21世紀最初の独立国"], exp:"コーヒー", flag:"🇹🇱", lon:125.56, lat:-8.56, size:"S" },

  // ===================== ヨーロッパ（追加） =====================
  { c:"北マケドニア", cap:"スコピエ", en:"Macedonia", cont:"ヨーロッパ", tier:3, fam:["オフリド湖"], exp:"鉄鋼", flag:"🇲🇰", lon:21.43, lat:41.99, size:"S" },
  { c:"アルバニア", cap:"ティラナ", en:"Albania", cont:"ヨーロッパ", tier:3, fam:["トーチカ(要塞)"], exp:"衣料品", flag:"🇦🇱", lon:19.82, lat:41.33, size:"S" },
  { c:"ボスニア・ヘルツェゴビナ", cap:"サラエボ", en:"Bosnia and Herz.", cont:"ヨーロッパ", tier:3, fam:["モスタルの橋"], exp:"金属", flag:"🇧🇦", lon:18.41, lat:43.86, size:"S" },
  { c:"モンテネグロ", cap:"ポドゴリツァ", en:"Montenegro", cont:"ヨーロッパ", tier:3, fam:["黒い山","コトル湾"], exp:"アルミ", flag:"🇲🇪", lon:19.26, lat:42.44, size:"S" },
  { c:"モルドバ", cap:"キシナウ", en:"Moldova", cont:"ヨーロッパ", tier:3, fam:["ワインの地下貯蔵庫"], exp:"ワイン", flag:"🇲🇩", lon:28.86, lat:47.01, size:"S" },
  { c:"マルタ", cap:"バレッタ", en:null, cont:"ヨーロッパ", tier:3, fam:["地中海の要塞島","マルタ騎士団"], exp:"電子機器", flag:"🇲🇹", lon:14.51, lat:35.9, size:"S" },
  { c:"キプロス", cap:"ニコシア", en:"Cyprus", cont:"ヨーロッパ", tier:3, fam:["アフロディーテ伝説","地中海リゾート"], exp:"医薬品", flag:"🇨🇾", lon:33.36, lat:35.17, size:"S" },
  { c:"モナコ", cap:"モナコ", en:null, cont:"ヨーロッパ", tier:2, fam:["F1モナコGP","カジノ"], exp:"化粧品", flag:"🇲🇨", lon:7.42, lat:43.74, size:"S" },
  { c:"アンドラ", cap:"アンドラ・ラ・ベリャ", en:null, cont:"ヨーロッパ", tier:3, fam:["ピレネー山脈のスキー"], exp:"タバコ", flag:"🇦🇩", lon:1.52, lat:42.51, size:"S" },
  { c:"サンマリノ", cap:"サンマリノ", en:null, cont:"ヨーロッパ", tier:3, fam:["世界最古の共和国"], exp:"切手・タイル", flag:"🇸🇲", lon:12.45, lat:43.94, size:"S" },
  { c:"リヒテンシュタイン", cap:"ファドゥーツ", en:null, cont:"ヨーロッパ", tier:3, fam:["アルプスの小国","切手"], exp:"精密機械", flag:"🇱🇮", lon:9.52, lat:47.14, size:"S" },

  // ===================== アフリカ（追加） =====================
  { c:"コンゴ共和国", cap:"ブラザビル", en:"Congo", cont:"アフリカ", tier:3, fam:["コンゴ川"], exp:"石油", flag:"🇨🇬", lon:15.28, lat:-4.27, size:"M" },
  { c:"ガボン", cap:"リーブルビル", en:"Gabon", cont:"アフリカ", tier:3, fam:["熱帯雨林","ゴリラ"], exp:"石油", flag:"🇬🇦", lon:9.45, lat:0.39, size:"M" },
  { c:"チャド", cap:"ンジャメナ", en:"Chad", cont:"アフリカ", tier:3, fam:["チャド湖"], exp:"石油", flag:"🇹🇩", lon:15.05, lat:12.11, size:"L" },
  { c:"ニジェール", cap:"ニアメ", en:"Niger", cont:"アフリカ", tier:3, fam:["サハラ砂漠"], exp:"ウラン", flag:"🇳🇪", lon:2.11, lat:13.51, size:"L" },
  { c:"ブルキナファソ", cap:"ワガドゥグー", en:"Burkina Faso", cont:"アフリカ", tier:3, fam:["アフリカ映画祭"], exp:"金・綿", flag:"🇧🇫", lon:-1.53, lat:12.37, size:"M" },
  { c:"ベナン", cap:"ポルトノボ", en:"Benin", cont:"アフリカ", tier:3, fam:["ブードゥー教発祥"], exp:"綿", flag:"🇧🇯", lon:2.63, lat:6.5, size:"S" },
  { c:"トーゴ", cap:"ロメ", en:"Togo", cont:"アフリカ", tier:3, fam:["細長い国"], exp:"リン鉱石", flag:"🇹🇬", lon:1.22, lat:6.14, size:"S" },
  { c:"ギニア", cap:"コナクリ", en:"Guinea", cont:"アフリカ", tier:3, fam:["ボーキサイト"], exp:"ボーキサイト", flag:"🇬🇳", lon:-13.71, lat:9.64, size:"M" },
  { c:"シエラレオネ", cap:"フリータウン", en:"Sierra Leone", cont:"アフリカ", tier:3, fam:["ダイヤモンド"], exp:"ダイヤ", flag:"🇸🇱", lon:-13.23, lat:8.48, size:"S" },
  { c:"リベリア", cap:"モンロビア", en:"Liberia", cont:"アフリカ", tier:3, fam:["解放奴隷が建てた国"], exp:"ゴム", flag:"🇱🇷", lon:-10.8, lat:6.3, size:"S" },
  { c:"モーリタニア", cap:"ヌアクショット", en:"Mauritania", cont:"アフリカ", tier:3, fam:["砂漠と鉄道"], exp:"鉄鉱石", flag:"🇲🇷", lon:-15.98, lat:18.08, size:"L" },
  { c:"ソマリア", cap:"モガディシュ", en:"Somalia", cont:"アフリカ", tier:3, fam:["アフリカの角"], exp:"家畜", flag:"🇸🇴", lon:45.34, lat:2.05, size:"M" },
  { c:"エリトリア", cap:"アスマラ", en:"Eritrea", cont:"アフリカ", tier:3, fam:["紅海の港"], exp:"鉱物", flag:"🇪🇷", lon:38.93, lat:15.34, size:"M" },
  { c:"ジブチ", cap:"ジブチ", en:"Djibouti", cont:"アフリカ", tier:3, fam:["アッサル湖"], exp:"中継貿易", flag:"🇩🇯", lon:43.15, lat:11.59, size:"S" },
  { c:"ブルンジ", cap:"ギテガ", en:"Burundi", cont:"アフリカ", tier:3, fam:["タンガニーカ湖"], exp:"コーヒー", flag:"🇧🇮", lon:29.92, lat:-3.43, size:"S" },
  { c:"マラウイ", cap:"リロングウェ", en:"Malawi", cont:"アフリカ", tier:3, fam:["マラウイ湖"], exp:"タバコ", flag:"🇲🇼", lon:33.79, lat:-13.96, size:"S" },
  { c:"レソト", cap:"マセル", en:"Lesotho", cont:"アフリカ", tier:3, fam:["天空の王国"], exp:"ダイヤ・衣料", flag:"🇱🇸", lon:27.48, lat:-29.31, size:"S" },
  { c:"エスワティニ", cap:"ムババーネ", en:"eSwatini", cont:"アフリカ", tier:3, fam:["アフリカ最後の絶対王政"], exp:"砂糖", flag:"🇸🇿", lon:31.13, lat:-26.32, size:"S" },
  { c:"ガンビア", cap:"バンジュール", en:"Gambia", cont:"アフリカ", tier:3, fam:["川に沿った細長い国"], exp:"落花生", flag:"🇬🇲", lon:-16.58, lat:13.45, size:"S" },
  { c:"赤道ギニア", cap:"マラボ", en:"Eq. Guinea", cont:"アフリカ", tier:3, fam:["スペイン語圏"], exp:"石油", flag:"🇬🇶", lon:8.78, lat:3.75, size:"S" },
  { c:"中央アフリカ", cap:"バンギ", en:"Central African Rep.", cont:"アフリカ", tier:3, fam:["熱帯雨林"], exp:"ダイヤ・木材", flag:"🇨🇫", lon:18.56, lat:4.39, size:"L" },
  { c:"南スーダン", cap:"ジュバ", en:"S. Sudan", cont:"アフリカ", tier:3, fam:["世界で最も新しい国"], exp:"石油", flag:"🇸🇸", lon:31.58, lat:4.85, size:"M" },
  { c:"モーリシャス", cap:"ポートルイス", en:null, cont:"アフリカ", tier:3, fam:["ドードー","インド洋リゾート"], exp:"砂糖", flag:"🇲🇺", lon:57.5, lat:-20.16, size:"S" },
  { c:"セーシェル", cap:"ビクトリア", en:null, cont:"アフリカ", tier:3, fam:["インド洋の楽園"], exp:"魚", flag:"🇸🇨", lon:55.45, lat:-4.62, size:"S" },
  { c:"カーボベルデ", cap:"プライア", en:null, cont:"アフリカ", tier:3, fam:["大西洋の島々","モルナ音楽"], exp:"魚", flag:"🇨🇻", lon:-23.51, lat:14.93, size:"S" },

  // ===================== 南アメリカ（追加） =====================
  { c:"ガイアナ", cap:"ジョージタウン", en:"Guyana", cont:"南アメリカ", tier:3, fam:["カイエトゥールの滝"], exp:"金・石油", flag:"🇬🇾", lon:-58.16, lat:6.8, size:"M" },
  { c:"スリナム", cap:"パラマリボ", en:"Suriname", cont:"南アメリカ", tier:3, fam:["南米で最小","熱帯雨林"], exp:"金", flag:"🇸🇷", lon:-55.17, lat:5.87, size:"M" },

  // ===================== 北アメリカ（追加） =====================
  { c:"ベリーズ", cap:"ベルモパン", en:"Belize", cont:"北アメリカ", tier:3, fam:["グレートブルーホール","サンゴ礁"], exp:"砂糖", flag:"🇧🇿", lon:-88.77, lat:17.25, size:"S" },
  { c:"バルバドス", cap:"ブリッジタウン", en:null, cont:"北アメリカ", tier:3, fam:["ラム酒発祥","カリブ海"], exp:"ラム酒", flag:"🇧🇧", lon:-59.62, lat:13.1, size:"S" },
  { c:"アンティグア・バーブーダ", cap:"セントジョンズ", en:null, cont:"北アメリカ", tier:3, fam:["365のビーチ"], exp:"観光", flag:"🇦🇬", lon:-61.85, lat:17.12, size:"S" },
  { c:"セントルシア", cap:"カストリーズ", en:null, cont:"北アメリカ", tier:3, fam:["ピトン山"], exp:"バナナ", flag:"🇱🇨", lon:-60.99, lat:14.01, size:"S" },
  { c:"グレナダ", cap:"セントジョージズ", en:null, cont:"北アメリカ", tier:3, fam:["ナツメグの島"], exp:"ナツメグ", flag:"🇬🇩", lon:-61.75, lat:12.05, size:"S" },
  { c:"ドミニカ国", cap:"ロゾー", en:null, cont:"北アメリカ", tier:3, fam:["自然の島"], exp:"バナナ", flag:"🇩🇲", lon:-61.39, lat:15.3, size:"S" },
  { c:"セントビンセント", cap:"キングスタウン", en:null, cont:"北アメリカ", tier:3, fam:["映画の撮影地"], exp:"バナナ", flag:"🇻🇨", lon:-61.22, lat:13.16, size:"S" },
  { c:"セントクリストファー・ネイビス", cap:"バセテール", en:null, cont:"北アメリカ", tier:3, fam:["南北アメリカ最小の国"], exp:"砂糖", flag:"🇰🇳", lon:-62.72, lat:17.3, size:"S" },
  { c:"コモロ", cap:"モロニ", en:null, cont:"アフリカ", tier:3, fam:["月の香りの島","バニラ"], exp:"バニラ", flag:"🇰🇲", lon:43.26, lat:-11.7, size:"S" },
  { c:"サントメ・プリンシペ", cap:"サントメ", en:null, cont:"アフリカ", tier:3, fam:["カカオの島"], exp:"カカオ", flag:"🇸🇹", lon:6.61, lat:0.34, size:"S" },
  { c:"コソボ", cap:"プリシュティナ", en:"Kosovo", cont:"ヨーロッパ", tier:3, fam:["ヨーロッパで最も新しい国"], exp:"金属", flag:"🇽🇰", lon:21.17, lat:42.67, size:"S" }
];
if (typeof module !== "undefined") module.exports = { COUNTRIES };
