name = "world-champion"
compatibility_date = "2025-06-01"
pages_build_output_dir = "."

# 下の id は「wrangler kv namespace create SCORES」で出てきたIDに置き換える
[[kv_namespaces]]
binding = "SCORES"
id = "ここにKV名前空間のIDを貼る"
